# .travis.yml
language: ruby
rvm:
  - 2.4.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  #- psql -c "CREATE USER Andrew WITH PASSWORD 'andrew';" -U postgres
  #- createuser -s -r Andrew
  #- psql -c 'create database Andrew' -U postgres
  - psql -c 'create database rubyBinaryTree_test' -U postgres
